<div class="park-review">

    <h4>Enter your review</h4>

    <form method="POST">

        <div class="park-review">

            <div class="rating">

                <input type="radio" id="rating5" name="rating">
                <label for="rating5"> &#9733;</label>
                <input type="radio" id="rating4" name="rating">
                <label for="rating4">&#9733;</label>
                <input type="radio" id="rating3" name="rating">
                <label for="rating3">&#9733;</label>
                <input type="radio" id="rating2" name="rating">
                <label for="rating2">&#9733;</label>
                <input type="radio" id="rating1" name="rating">
                <label for="rating1">&#9733;</label>
            </div>
            <br>
            <textarea cols="50" rows="4" name="review-text" placeholder="Enter your review here."></textarea>
        </div>
        <input type="submit" value="Submit">
    </form>

</div>