<header>
    <div class="header">
        <h1>Park Search</h1>
        <nav>
            <ul>
                <li><a href="index.php">Home</a></li>
                <li><a href="browse.php">Browse</a></li>
                <li><a href="create-account.php">Create Account</a></li>
                <li><a href="login.php">Login</a></li>
				<li><a href="logout.php">Logout</a></li>
                <li><a href="results.php">Results</a></li>
            </ul>
        </nav>
    </div>
</header>